# Generated by Django 5.2.4 on 2025-07-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('university_code', models.CharField(max_length=50, unique=True)),
                ('establishment_year', models.CharField(max_length=10)),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('contact_info', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('governance_structure', models.JSONField(blank=True, null=True)),
                ('policies', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=50, unique=True)),
                ('school_type', models.CharField(max_length=100)),
                ('establishment_year', models.CharField(max_length=10)),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('vision_mission', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_schools', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='universityapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('department_code', models.CharField(max_length=50, unique=True)),
                ('department_type', models.CharField(max_length=100)),
                ('research_areas', models.JSONField(blank=True, null=True)),
                ('facilities', models.JSONField(blank=True, null=True)),
                ('collaborations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universityapp.school')),
            ],
        ),
    ]
